steps:
  # Docker 이미지 빌드
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'asia-northeast3-docker.pkg.dev/flash-physics-368407/lyt-test/crypto-app:latest', '.']

  # Docker 이미지 Artifact Registry에 푸시
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'asia-northeast3-docker.pkg.dev/flash-physics-368407/lyt-test/crypto-app:latest']

images:
  - 'asia-northeast3-docker.pkg.dev/flash-physics-368407/lyt-test/crypto-app:latest'
