steps:
  # Docker 이미지 빌드
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', '${_IMAGE_NAME}:$SHORT_SHA', '.']

  # Docker 이미지 Artifact Registry에 푸시
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', '${_IMAGE_NAME}:$SHORT_SHA']

images:
  - '${_IMAGE_NAME}:$SHORT_SHA'
